//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;

namespace Mobility.WebForms.Views.Employee
{


    public partial class Employee
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gridEmployees;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.TextBox txtMailAddress;
        protected global::System.Web.UI.WebControls.TextBox txtSalary;
        protected global::System.Web.UI.WebControls.TextBox txtAge;
        protected global::System.Web.UI.WebControls.TextBox txtEditFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtEditLastName;
        protected global::System.Web.UI.WebControls.TextBox txtEditMailAddress;
        protected global::System.Web.UI.WebControls.TextBox txtEditSalary;
        protected global::System.Web.UI.WebControls.TextBox txtEditAge;
    }
}
